baseURL = "https://www.usbmdistros.com/"
languageCode = "en-us"
title = "US Black Metal Distributors"
theme = "bmstore"

[author]
    name = "U.S. Black Metal Distributor Index"

[Params]
    paginate = 48